### ISSUE TITLE
Crash on Game start

### ISSUE THREAD

**Issue by MasterEnderman** [terrapin47/TinkeringWithBloodMagic#4]
Crash-Report: https://paste.dimdev.org/mibuqamowi.mccrash
TinkeringWithBloodMagic: 1.0.0
Forge: 14.23.5.2772

**Comment by terrapin47** [comment]
Looking into it now

**Comment by MasterEnderman** [comment]
I disabled the smeltery module in TiCo. I think that's causing the crash.

**Comment by terrapin47** [comment]
Oh, that makes sense.  I'll account for that too, thanks.

**Comment by terrapin47** [comment]
Have a fix coming, I suppose you're making custom recipes to accommodate for no Smeltery?

**Comment by MasterEnderman** [comment]
Exactly. I wrote a CraftTweaker Script to generate Recipes for all Toolparts.

**Comment by terrapin47** [comment]
Alright, cool thanks.
Fixed in https://github.com/terrapin47/TinkeringWithBloodMagic/commit/6ddff20e82025fcb03596514720b118358ae3837 and curseforge should update soon.
