### ISSUE TITLE
Crash on server

### ISSUE THREAD

**Issue by pupnewfster** [terrapin47/TinkeringWithBloodMagic#5]
Client rendering code attempting to be loaded on server:

https://pastebin.com/yQ1j4k3J

Version: 1.0.1
Forge : 14.23.5.2772

**Comment by terrapin47** [comment]
Fixed in https://github.com/terrapin47/TinkeringWithBloodMagic/commit/45bbf60d4a11e2a6dea86df458532783236f0b13

Thanks for the report
